import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { Image, Title, Group, ActionIcon, Button, MantineProvider , Text} from '@mantine/core'
import Links from '../api/links.json'
import Grid_data from '../api/grid.json'
import stats from '../api/stats.json'
import authors from '../api/authors.json'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
     </main>
    </div>
  )
}

export default Home


const redirectToLink = (link: string): void => {
  window.open(link, '_blank');
};